/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole.ManageReportsAnalytics;

import Business.Business;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import Business.Profiles.StudentProfile;
import java.util.HashMap;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anush
 */
public class ManageReportsAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageReportsAnalyticsJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    
    public ManageReportsAnalyticsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateReportTypeCombo();
        clearTables();
    }
    
    // --- Initialize combo box ---
    private void populateReportTypeCombo() {
        cmbReportType.removeAllItems();
        cmbReportType.addItem("-- Select Report --");
        cmbReportType.addItem("Enrollment by Department / Course");
        cmbReportType.addItem("GPA Distribution by Program");
    }

    // --- Clear both tables ---
    private void clearTables() {
        ((DefaultTableModel) tblEnrollmentReport1.getModel()).setRowCount(0);
        ((DefaultTableModel) tblGPAReport.getModel()).setRowCount(0);
        txtSummaryTitle.setText("");
        txtTotalEnrollments.setText("");
        txtAverageGPA.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblReportType = new javax.swing.JLabel();
        cmbReportType = new javax.swing.JComboBox<>();
        btnGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGPAReport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnrollmentReport1 = new javax.swing.JTable();
        lblSummaryTitle = new javax.swing.JLabel();
        lblTotalEnrollments = new javax.swing.JLabel();
        lblAverageGPA = new javax.swing.JLabel();
        txtSummaryTitle = new javax.swing.JTextField();
        txtTotalEnrollments = new javax.swing.JTextField();
        txtAverageGPA = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 204, 204));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setText("Institutional Reports & Analytics");

        lblReportType.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblReportType.setText("Select Report Type");

        cmbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        tblGPAReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Program", "Student ID", "Name", "GPA", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGPAReport.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblGPAReport);

        tblEnrollmentReport1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Department", "Course ID", "Course Name", "Semester", "Total Enrollments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnrollmentReport1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblEnrollmentReport1);

        lblSummaryTitle.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblSummaryTitle.setText("Summary:");

        lblTotalEnrollments.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblTotalEnrollments.setText("Total Enrollments:");

        lblAverageGPA.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblAverageGPA.setText("Average GPA:");

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblReportType)
                        .addGap(34, 34, 34)
                        .addComponent(cmbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblSummaryTitle)
                                .addGap(27, 27, 27)
                                .addComponent(txtSummaryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(lblTitle))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblTotalEnrollments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalEnrollments, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAverageGPA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAverageGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnGenerate)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportType)
                    .addComponent(cmbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnGenerate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSummaryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSummaryTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalEnrollments)
                    .addComponent(lblAverageGPA)
                    .addComponent(txtTotalEnrollments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAverageGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        clearTables();
        String selectedReport = (String) cmbReportType.getSelectedItem();

        if (selectedReport == null || selectedReport.equals("-- Select Report --")) {
            JOptionPane.showMessageDialog(this, "Please select a report type.");
            return;
        }

        if (selectedReport.contains("Enrollment")) {
            loadEnrollmentReport();
        } else if (selectedReport.contains("GPA")) {
            loadGPAReport();
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    
    private void loadEnrollmentReport() {
        DefaultTableModel model = (DefaultTableModel) tblEnrollmentReport1.getModel();
        model.setRowCount(0);

        HashMap<String, CourseSchedule> schedules = business.getMasterCourseCatalog();
        int totalEnrollments = 0;

        for (String semester : schedules.keySet()) {
            CourseSchedule cs = schedules.get(semester);

            for (CourseOffer co : cs.getSchedule()) {
                int enrolled = co.getEnrolledCount();
                String dept = co.getSubjectCourse().getCourseNumber().substring(0, 4); // example dept code

                Object[] row = new Object[5];
                row[0] = dept;
                row[1] = co.getCourseNumber();
                row[2] = co.getSubjectCourse().getName();
                row[3] = semester;
                row[4] = enrolled;
                model.addRow(row);

                totalEnrollments += enrolled;
            }
        }

        txtSummaryTitle.setText("Summary for Enrollment Report");
        txtTotalEnrollments.setText(String.valueOf(totalEnrollments));
        txtAverageGPA.setText("N/A");
    }

    // --- GPA Distribution Report ---
    private void loadGPAReport() {
        DefaultTableModel model = (DefaultTableModel) tblGPAReport.getModel();
        model.setRowCount(0);

        double totalGPA = 0.0;
        int studentCount = 0;
        Random random = new Random();

        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {
            double gpa = 2.5 + (random.nextDouble() * 1.5); // random GPA between 2.5–4.0
            String status = gpa >= 3.0 ? "Good Standing" : "Warning";

            Object[] row = new Object[5];
            row[0] = sp.getProgram() != null ? sp.getProgram() : "MSIS";
            row[1] = sp.getPerson().getPersonId();
            row[2] = sp.getPerson().getName();
            row[3] = String.format("%.2f", gpa);
            row[4] = status;
            model.addRow(row);

            totalGPA += gpa;
            studentCount++;
        }

        double avgGPA = (studentCount > 0) ? totalGPA / studentCount : 0.0;
        txtSummaryTitle.setText("Summary for GPA Report");
        txtTotalEnrollments.setText(String.valueOf(studentCount));
        txtAverageGPA.setText(String.format("%.2f", avgGPA));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> cmbReportType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAverageGPA;
    private javax.swing.JLabel lblReportType;
    private javax.swing.JLabel lblSummaryTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalEnrollments;
    private javax.swing.JTable tblEnrollmentReport1;
    private javax.swing.JTable tblGPAReport;
    private javax.swing.JTextField txtAverageGPA;
    private javax.swing.JTextField txtSummaryTitle;
    private javax.swing.JTextField txtTotalEnrollments;
    // End of variables declaration//GEN-END:variables
}
