/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import Business.Profiles.RegistrarProfile;
import Business.UserAccounts.UserAccount;
import UserInterface.WorkAreas.RegistrarRole.ManageCourse.ManageCourseJPanel;
import UserInterface.WorkAreas.RegistrarRole.ManageReportsAnalytics.ManageReportsAnalyticsJPanel;
import UserInterface.WorkAreas.RegistrarRole.ManageStudentEnrollment.ManageStudentEnrollmentJPanel;
import UserInterface.WorkAreas.RegistrarRole.ManageTuitionReconciliation.ManageTuitionReconciliationJPanel;
import UserInterface.WorkAreas.RegistrarRole.RegistrarProfile.RegistrarProfileJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anush
 */
public class RegistrarRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarRoleWorkAreaJPanel
     */
    
    private Business business;
    private RegistrarProfile registrar;
    private UserAccount userAccount;
    private JPanel CardSequencePanel;

    public RegistrarRoleWorkAreaJPanel(Business b,RegistrarProfile p,  UserAccount ua, JPanel CardSequencePanel) {
        initComponents();
        this.business = b;
        this.registrar = p;
        this.userAccount = ua;
        this.CardSequencePanel = CardSequencePanel;
        initComponents();
        
        jLabel1.setText("Welcome, " + registrar.getPerson().getName() + " (Registrar)");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageCourse = new javax.swing.JButton();
        btnMyRegProfile = new javax.swing.JButton();
        btnStudentEnrollment = new javax.swing.JButton();
        btnTutionReconciliation = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N

        btnManageCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourse.setText("Manage Course");
        btnManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourse.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageCourse.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnMyRegProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyRegProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyRegProfile.setText("My Profile");
        btnMyRegProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyRegProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMyRegProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyRegProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyRegProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyRegProfileActionPerformed(evt);
            }
        });

        btnStudentEnrollment.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentEnrollment.setText("Student Enrollment");
        btnStudentEnrollment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentEnrollment.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentEnrollment.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentEnrollment.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentEnrollmentActionPerformed(evt);
            }
        });

        btnTutionReconciliation.setBackground(new java.awt.Color(102, 153, 255));
        btnTutionReconciliation.setForeground(new java.awt.Color(255, 255, 255));
        btnTutionReconciliation.setText("Tution & Reconciliation");
        btnTutionReconciliation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTutionReconciliation.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTutionReconciliation.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTutionReconciliation.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTutionReconciliation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutionReconciliationActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(102, 153, 255));
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("Reports & Analytics");
        btnReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport.setMaximumSize(new java.awt.Dimension(145, 40));
        btnReport.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReport.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportIdentifyEventsActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 51, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMyRegProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTutionReconciliation, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(624, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyRegProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTutionReconciliation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCourseIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        
         ManageCourseJPanel manageCoursePanel = new ManageCourseJPanel(business, CardSequencePanel);
    CardSequencePanel.add("ManageCoursePanel", manageCoursePanel);
    ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    
    }//GEN-LAST:event_btnManageCourseIdentifyResourceAssetsActionPerformed

    private void btnMyRegProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyRegProfileActionPerformed
        // TODO add your handling code here:
        RegistrarProfileJPanel app = new RegistrarProfileJPanel(business, registrar, userAccount, CardSequencePanel);
    CardSequencePanel.add("RegistrarProfile", app);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    
    }//GEN-LAST:event_btnMyRegProfileActionPerformed

    private void btnStudentEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentEnrollmentActionPerformed
        // TODO add your handling code here:
         ManageStudentEnrollmentJPanel msejp = new ManageStudentEnrollmentJPanel(business, CardSequencePanel);
    CardSequencePanel.add("ManageStudentEnrollmentJPanel", msejp);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnStudentEnrollmentActionPerformed

    private void btnTutionReconciliationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutionReconciliationActionPerformed
        // TODO add your handling code here:
        ManageTuitionReconciliationJPanel mtrjp = new ManageTuitionReconciliationJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageTuitionReconciliationJPanel", mtrjp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnTutionReconciliationActionPerformed

    private void btnReportIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportIdentifyEventsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();
        ManageReportsAnalyticsJPanel mrajp = new ManageReportsAnalyticsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageReportsAnalyticsJPanel", mrajp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
         
      
        
    }//GEN-LAST:event_btnReportIdentifyEventsActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            // Remove all panels from CardSequencePanel
            CardSequencePanel.removeAll();

            // Recreate the welcome label (same as original)
            javax.swing.JLabel welcomeLabel = new javax.swing.JLabel();
            welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 24));
            welcomeLabel.setForeground(new java.awt.Color(102, 153, 255));
            welcomeLabel.setText("Education Going Digital .... Info 5100");

            // Add it back with the proper name
            CardSequencePanel.add(welcomeLabel, "WelcomeScreen");

            // Show the welcome screen
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.show(CardSequencePanel, "WelcomeScreen");

            // Force UI refresh
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnMyRegProfile;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStudentEnrollment;
    private javax.swing.JButton btnTutionReconciliation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
