/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
* WorkAreaJPanel.java
*
* Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.AdminProfile.AdminProfileJPanel;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.AnalyticsDashboard.AnalyticsDashboardJPanel;
import UserInterface.WorkAreas.AdminRole.ManageFacultyWorkResp.ManageFacultyCourseAssignmentsJPanel;
import UserInterface.WorkAreas.AdminRole.ManageFacultyWorkResp.ManageFacultyJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.RegisterPersonJPanel;
import UserInterface.WorkAreas.AdminRole.ManageRegistrarWorkResp.ManageRegistrarJPanel;
import UserInterface.WorkAreas.AdminRole.ManageStudentsWorkResp.ManageStudentsJPanel;
import java.awt.CardLayout;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    UserAccount currentUserAccount;  // NEW - store current user

    /**
     * Creates new form UnitRiskWorkArea
     */
    public AdminRoleWorkAreaJPanel(Business b, JPanel clp, UserAccount ua) { // Add ua parameter

        business = b;
        this.CardSequencePanel = clp;
        this.currentUserAccount = ua;  // NEW - store it
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        manageRegistrar = new javax.swing.JButton();
        analyticsButton1 = new javax.swing.JButton();
        myProfileButton1 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        assignFacultyButton = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(getFont());
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Administer User Accounts");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(20, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(240, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 153, 255));
        jButton9.setFont(getFont());
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Manage Faculty");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton9.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton9.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 153, 255));
        jButton10.setFont(getFont());
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Register  Persons (HR)");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton10.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton10.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 153, 255));
        jButton8.setFont(getFont());
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Manage Students");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton8.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton8.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        manageRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        manageRegistrar.setFont(getFont());
        manageRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        manageRegistrar.setText("Manage Registrar");
        manageRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageRegistrar.setMaximumSize(new java.awt.Dimension(145, 40));
        manageRegistrar.setMinimumSize(new java.awt.Dimension(20, 20));
        manageRegistrar.setPreferredSize(new java.awt.Dimension(240, 25));
        manageRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRegistrarIdentifyEventsActionPerformed(evt);
            }
        });

        analyticsButton1.setBackground(new java.awt.Color(102, 153, 255));
        analyticsButton1.setFont(getFont());
        analyticsButton1.setForeground(new java.awt.Color(255, 255, 255));
        analyticsButton1.setText("Analytics Dashboard");
        analyticsButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analyticsButton1.setMaximumSize(new java.awt.Dimension(145, 40));
        analyticsButton1.setMinimumSize(new java.awt.Dimension(20, 20));
        analyticsButton1.setPreferredSize(new java.awt.Dimension(240, 25));
        analyticsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsButton1IdentifyEventsActionPerformed(evt);
            }
        });

        myProfileButton1.setBackground(new java.awt.Color(102, 153, 255));
        myProfileButton1.setFont(getFont());
        myProfileButton1.setForeground(new java.awt.Color(255, 255, 255));
        myProfileButton1.setText("My Profile");
        myProfileButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        myProfileButton1.setMaximumSize(new java.awt.Dimension(145, 40));
        myProfileButton1.setMinimumSize(new java.awt.Dimension(20, 20));
        myProfileButton1.setPreferredSize(new java.awt.Dimension(240, 25));
        myProfileButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButton1IdentifyEventsActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 51, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        assignFacultyButton.setBackground(new java.awt.Color(102, 153, 255));
        assignFacultyButton.setFont(getFont());
        assignFacultyButton.setForeground(new java.awt.Color(255, 255, 255));
        assignFacultyButton.setText("Faculty Course Assignment");
        assignFacultyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assignFacultyButton.setMaximumSize(new java.awt.Dimension(200, 40));
        assignFacultyButton.setMinimumSize(new java.awt.Dimension(20, 20));
        assignFacultyButton.setPreferredSize(new java.awt.Dimension(240, 25));
        assignFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignFacultyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assignFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(644, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRegistrarIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRegistrarIdentifyEventsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        ManageRegistrarJPanel mrp = new ManageRegistrarJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageRegistrar", mrp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_manageRegistrarIdentifyEventsActionPerformed

    private void analyticsButton1IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsButton1IdentifyEventsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        AnalyticsDashboardJPanel adp = new AnalyticsDashboardJPanel(business, CardSequencePanel);

        CardSequencePanel.add("AnalyticsDashboard", adp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_analyticsButton1IdentifyEventsActionPerformed

    private void myProfileButton1IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButton1IdentifyEventsActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        AdminProfileJPanel app = new AdminProfileJPanel(business, CardSequencePanel, currentUserAccount);

        CardSequencePanel.add("AdminProfile", app);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_myProfileButton1IdentifyEventsActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            // Remove all panels from CardSequencePanel
            CardSequencePanel.removeAll();

            // Recreate the welcome label (same as original)
            javax.swing.JLabel welcomeLabel = new javax.swing.JLabel();
            welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 24));
            welcomeLabel.setForeground(new java.awt.Color(102, 153, 255));
            welcomeLabel.setText("Education Going Digital .... Info 5100");

            // Add it back with the proper name
            CardSequencePanel.add(welcomeLabel, "WelcomeScreen");

            // Show the welcome screen
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.show(CardSequencePanel, "WelcomeScreen");

            // Force UI refresh
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void assignFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignFacultyButtonActionPerformed
        // TODO add your handling code here:
        ManageFacultyCourseAssignmentsJPanel mfca = new ManageFacultyCourseAssignmentsJPanel(business, CardSequencePanel);
        CardSequencePanel.add(mfca, "FacultyCourseAssignments");
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "FacultyCourseAssignments");
    }//GEN-LAST:event_assignFacultyButtonActionPerformed

    private void jButton4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }// GEN-LAST:event_jButton4IdentifyResourceAssetsActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        RegisterPersonJPanel rpp = new RegisterPersonJPanel(business, CardSequencePanel);

        CardSequencePanel.add("RegisterPerson", rpp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }// GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        ManageStudentsJPanel msp = new ManageStudentsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageStudents", msp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }// GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.removeAll();

        ManageFacultyJPanel mfp = new ManageFacultyJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageFaculty", mfp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }// GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsButton1;
    private javax.swing.JButton assignFacultyButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageRegistrar;
    private javax.swing.JButton myProfileButton1;
    // End of variables declaration//GEN-END:variables

}
