/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Profiles.StudentProfile;
import ManageStudentModel.TranscriptRecord;
import StudentUtils.GradeUtils;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

/**
 *
 * @author Amrin
 */
public class StudentTranscript extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private JTable tblTranscript;
    private JComboBox<String> cmbTermFilter;
    private JLabel lblTermGPA, lblOverallGPA, lblStanding;
    private ArrayList<TranscriptRecord> transcriptList;
    /**
     * Creates new form StudentTranscript
     */
    private StudentProfile student;
    public StudentTranscript(StudentProfile student) {
        this.student = student;
        this.CardSequencePanel = CardSequencePanel;
        transcriptList = new ArrayList<>();
        initComponents();
        populateDummyData();
        populateTable(null);
    }
private void populateTable(String termFilter) {
    DefaultTableModel model = (DefaultTableModel) tbltrans.getModel();
    model.setRowCount(0);

    double totalQualityPointsAll = 0, totalCreditsAll = 0;
    double totalQualityPointsTerm = 0, totalCreditsTerm = 0;

    for (TranscriptRecord tr : transcriptList) {
        double gradePoints = GradeUtils.getPoints(tr.getGrade());
        double qualityPoints = gradePoints * tr.getCreditHours();

        totalQualityPointsAll += qualityPoints;
        totalCreditsAll += tr.getCreditHours();

        if (termFilter == null || tr.getTerm().equals(termFilter)) {
            totalQualityPointsTerm += qualityPoints;
            totalCreditsTerm += tr.getCreditHours();
        }
    }

    double overallGPA = totalCreditsAll > 0 ? totalQualityPointsAll / totalCreditsAll : 0;
    double termGPA = totalCreditsTerm > 0 ? totalQualityPointsTerm / totalCreditsTerm : 0;

    String standing = "Good Standing";
    if (overallGPA < 3.0) standing = "Academic Probation";
    else if (termGPA < 3.0) standing = "Academic Warning";

    fieldgpa.setText(String.format("%.2f", termGPA));
    fieldogpa.setText(String.format("%.2f", overallGPA));
    fieldstand.setText(standing);

    for (TranscriptRecord tr : transcriptList) {
        if (termFilter == null || tr.getTerm().equals(termFilter)) {
            model.addRow(new Object[]{
                tr.getTerm(), tr.getCourseId(), tr.getCourseName(), tr.getGrade(),
                String.format("%.2f", termGPA), String.format("%.2f", overallGPA), standing
            });
        }
    }
}
private void populateDummyData() {
    transcriptList.add(new TranscriptRecord("Fall 2025", "INFO 5100", "Application Engineering and Development", "A", 4));
    transcriptList.add(new TranscriptRecord("Fall 2025", "INFO 6205", "Program Structure & Algorithms", "B+", 4));
    transcriptList.add(new TranscriptRecord("Spring 2026", "INFO 6105", "Data Science Engineering Methods", "A-", 3));
    transcriptList.add(new TranscriptRecord("Spring 2026", "INFO 6150", "Web Design & UX", "B", 3));

    // Add terms to combo box
    comboterm.removeAllItems();
    comboterm.addItem("All Terms");

    Set<String> terms = new HashSet<>();
    for (TranscriptRecord tr : transcriptList) {
        terms.add(tr.getTerm());
    }
    for (String term : terms) {
        comboterm.addItem(term);
    }

    comboterm.addActionListener(e -> {
        String selectedTerm = (String) comboterm.getSelectedItem();
        populateTable(selectedTerm.equals("All Terms") ? null : selectedTerm);
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        lblterm = new javax.swing.JLabel();
        comboterm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltrans = new javax.swing.JTable();
        lbltermg = new javax.swing.JLabel();
        fieldgpa = new javax.swing.JTextField();
        lblogpa = new javax.swing.JLabel();
        fieldogpa = new javax.swing.JTextField();
        lblaca = new javax.swing.JLabel();
        fieldstand = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitle.setText("TRANSCRIPT REVIEW");

        lblterm.setText("Select Term");

        comboterm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotermActionPerformed(evt);
            }
        });

        tbltrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Term", "Course ID", "Course Name", "Grade", "Term GPA", "Overall GPA", "Standing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbltrans);

        lbltermg.setText("Term GPA");

        lblogpa.setText("Overall GPA");

        fieldogpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldogpaActionPerformed(evt);
            }
        });

        lblaca.setText("Academic Standing");

        fieldstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldstandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbltermg)
                .addGap(18, 18, 18)
                .addComponent(fieldgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblogpa)
                .addGap(18, 18, 18)
                .addComponent(fieldogpa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblterm)
                                .addGap(26, 26, 26)
                                .addComponent(comboterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnback)
                                .addGap(122, 122, 122)
                                .addComponent(lbltitle))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldstand, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(lbltitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblterm)
                    .addComponent(comboterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltermg)
                    .addComponent(fieldgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblogpa)
                    .addComponent(fieldogpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaca)
                    .addComponent(fieldstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.previous(this.getParent());
    }//GEN-LAST:event_btnbackActionPerformed

    private void combotermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotermActionPerformed

    private void fieldogpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldogpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldogpaActionPerformed

    private void fieldstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldstandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldstandActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> comboterm;
    private javax.swing.JTextField fieldgpa;
    private javax.swing.JTextField fieldogpa;
    private javax.swing.JTextField fieldstand;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaca;
    private javax.swing.JLabel lblogpa;
    private javax.swing.JLabel lblterm;
    private javax.swing.JLabel lbltermg;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tbltrans;
    // End of variables declaration//GEN-END:variables
}
