/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Amrin
 */
public class StudentManageProfile extends javax.swing.JPanel {


    /**
     * Creates new form StudentManageProfile
     */
private StudentProfile student;

public StudentManageProfile(StudentProfile student) {
    this.student = student;
        initComponents();
        loadStudentData();
        setFieldsEditable(false); // make text fields read-only initially
    }

    private void loadStudentData() {
    fieldname.setText(student.getPerson().getName());
    fieldemail.setText(student.getPerson().getEmail());
    fieldphone.setText(student.getPerson().getPhone());
    fieldaddress.setText(student.getPerson().getAddress());
    fieldprogram.setText(student.getProgram());
}

private void setFieldsEditable(boolean editable) {
    fieldname.setEditable(editable);
    fieldphone.setEditable(editable);
    fieldemail.setEditable(editable);
    fieldaddress.setEditable(editable);
    fieldprogram.setEditable(editable);

    java.awt.Color bg = editable ? java.awt.Color.white : new java.awt.Color(230,230,230);
    fieldname.setBackground(bg);
    fieldphone.setBackground(bg);
    fieldemail.setBackground(bg);
    fieldaddress.setBackground(bg);
    fieldprogram.setBackground(bg);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblprogram = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        fieldname = new javax.swing.JTextField();
        fieldphone = new javax.swing.JTextField();
        fieldemail = new javax.swing.JTextField();
        fieldaddress = new javax.swing.JTextField();
        fieldprogram = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("STUDENT PROFILE");

        lblname.setText("Name");

        lblphone.setText("Phone");

        lblemail.setText("Email");

        lbladdress.setText("Address");

        lblprogram.setText("Program");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        fieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldemailActionPerformed(evt);
            }
        });

        fieldaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldaddressActionPerformed(evt);
            }
        });

        fieldprogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldprogramActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnback)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblprogram)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblphone)
                                .addComponent(lblname)
                                .addComponent(lblemail)
                                .addComponent(lbladdress)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldname, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(fieldphone)
                            .addComponent(fieldemail)
                            .addComponent(fieldaddress)
                            .addComponent(fieldprogram)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnEdit)
                        .addGap(44, 44, 44)
                        .addComponent(btnSave)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(fieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(fieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdress)
                    .addComponent(fieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprogram)
                    .addComponent(fieldprogram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    setFieldsEditable(true);
    JOptionPane.showMessageDialog(this, "You can now edit your profile details.");
    }//GEN-LAST:event_btnEditActionPerformed

    private void fieldaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldaddressActionPerformed

    private void fieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldemailActionPerformed

    private void fieldprogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldprogramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldprogramActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    // Update the StudentProfile with the values from the text fields
    student.getPerson().setName(fieldname.getText().trim());
    student.getPerson().setEmail(fieldemail.getText().trim());
    student.getPerson().setPhone(fieldphone.getText().trim());
    student.getPerson().setAddress(fieldaddress.getText().trim());
    student.setProgram(fieldprogram.getText().trim());
    
    // After saving, lock fields again
    setFieldsEditable(false);
    
    // Confirmation message
    JOptionPane.showMessageDialog(this, "Profile updated successfully!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    CardLayout layout = (CardLayout) this.getParent().getLayout();
    layout.previous(this.getParent());
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnback;
    private javax.swing.JTextField fieldaddress;
    private javax.swing.JTextField fieldemail;
    private javax.swing.JTextField fieldname;
    private javax.swing.JTextField fieldphone;
    private javax.swing.JTextField fieldprogram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblprogram;
    // End of variables declaration//GEN-END:variables
}
