/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Profiles.StudentProfile;
import ManageStudentModel.Course;
import ManageStudentModel.Student;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amrin
 */
public class StudentGraduation extends javax.swing.JPanel {
private StudentProfile student;
    /**
     * Creates new form StudentGraduation
     */
public StudentGraduation(StudentProfile student) {
    this.student = student;
    initComponents();
    populateTable();
}
private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tablegrad.getModel();
    model.setRowCount(0); // clear table first

    for (Course c : student.getEnrolledCourses()) {
        model.addRow(new Object[]{c.getCourseId(), c.getCourseName(), c.getCredits(), "Semester X"});
    }

    fieldcredits.setText(String.valueOf(student.getTotalCredits()));
}
private void checkEligibility() {
    if (student.isEligibleToGraduate()) {
        JOptionPane.showMessageDialog(this, "✅ Eligible to Graduate!", "Graduation Status", JOptionPane.INFORMATION_MESSAGE);
    } else {
        StringBuilder msg = new StringBuilder("❌ Not Eligible to Graduate:\n");
        if (!student.hasCoreCourse()) msg.append("- Core course INFO 5100 missing\n");
        if (student.getTotalCredits() < 32) msg.append("- Total credits less than 32\n");
        JOptionPane.showMessageDialog(this, msg.toString(), "Graduation Status", JOptionPane.WARNING_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Courseofferingtable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablegrad = new javax.swing.JTable();
        btneligible = new javax.swing.JButton();
        lbltotalcreditscomplete = new javax.swing.JLabel();
        fieldcredits = new javax.swing.JTextField();

        Courseofferingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Instructor", "Credit", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Courseofferingtable);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitle.setText("GRADUATION AUDIT");

        tablegrad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Credit", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablegrad);

        btneligible.setText("Check Eligibility");
        btneligible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneligibleActionPerformed(evt);
            }
        });

        lbltotalcreditscomplete.setText("Total Credits Completed:");

        fieldcredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcreditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnback)
                        .addGap(90, 90, 90)
                        .addComponent(lbltitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbltotalcreditscomplete)
                        .addGap(18, 18, 18)
                        .addComponent(fieldcredits, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btneligible))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle)
                    .addComponent(btnback))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotalcreditscomplete)
                    .addComponent(fieldcredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btneligible)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.previous(this.getParent());
    }//GEN-LAST:event_btnbackActionPerformed

    private void btneligibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneligibleActionPerformed
        // TODO add your handling code here:
    checkEligibility();
    }//GEN-LAST:event_btneligibleActionPerformed

    private void fieldcreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcreditsActionPerformed
        // TODO add your handling code here:
        fieldcredits.setText(String.valueOf(student.getTotalCredits()));
    }//GEN-LAST:event_fieldcreditsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Courseofferingtable;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btneligible;
    private javax.swing.JTextField fieldcredits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltotalcreditscomplete;
    private javax.swing.JTable tablegrad;
    // End of variables declaration//GEN-END:variables
}
