/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.StudentRole;
import UserInterface.WorkAreas.StudentRole.StudentManageProfile;
import java.awt.CardLayout;
import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        student = spp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanagefinance = new javax.swing.JButton();
        btnmanageprofile = new javax.swing.JButton();
        btngradaudit = new javax.swing.JButton();
        btnregistration = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btntranscript = new javax.swing.JButton();
        btncoursework = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));

        btnmanagefinance.setBackground(new java.awt.Color(102, 153, 255));
        btnmanagefinance.setFont(getFont());
        btnmanagefinance.setForeground(new java.awt.Color(255, 255, 255));
        btnmanagefinance.setText("Manage Finance");
        btnmanagefinance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmanagefinance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnmanagefinance.setMinimumSize(new java.awt.Dimension(20, 23));
        btnmanagefinance.setPreferredSize(new java.awt.Dimension(240, 30));
        btnmanagefinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagefinanceIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnmanageprofile.setBackground(new java.awt.Color(102, 153, 255));
        btnmanageprofile.setFont(getFont());
        btnmanageprofile.setForeground(new java.awt.Color(255, 255, 255));
        btnmanageprofile.setText("Manage Profile");
        btnmanageprofile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmanageprofile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnmanageprofile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnmanageprofile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnmanageprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageprofileActionPerformed(evt);
            }
        });

        btngradaudit.setBackground(new java.awt.Color(102, 153, 255));
        btngradaudit.setFont(getFont());
        btngradaudit.setForeground(new java.awt.Color(255, 255, 255));
        btngradaudit.setText("Graduation Audit");
        btngradaudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btngradaudit.setMaximumSize(new java.awt.Dimension(200, 40));
        btngradaudit.setMinimumSize(new java.awt.Dimension(20, 20));
        btngradaudit.setPreferredSize(new java.awt.Dimension(240, 25));
        btngradaudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngradauditActionPerformed(evt);
            }
        });

        btnregistration.setBackground(new java.awt.Color(102, 153, 255));
        btnregistration.setFont(getFont());
        btnregistration.setForeground(new java.awt.Color(255, 255, 255));
        btnregistration.setText("Registration");
        btnregistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnregistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnregistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("My Student Portal");

        btntranscript.setBackground(new java.awt.Color(102, 153, 255));
        btntranscript.setFont(getFont());
        btntranscript.setForeground(new java.awt.Color(255, 255, 255));
        btntranscript.setText("Transcript");
        btntranscript.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntranscript.setMaximumSize(new java.awt.Dimension(200, 40));
        btntranscript.setMinimumSize(new java.awt.Dimension(20, 20));
        btntranscript.setPreferredSize(new java.awt.Dimension(240, 25));
        btntranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranscriptActionPerformed(evt);
            }
        });

        btncoursework.setBackground(new java.awt.Color(102, 153, 255));
        btncoursework.setFont(getFont());
        btncoursework.setForeground(new java.awt.Color(255, 255, 255));
        btncoursework.setText("Course Work");
        btncoursework.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncoursework.setMaximumSize(new java.awt.Dimension(200, 40));
        btncoursework.setMinimumSize(new java.awt.Dimension(20, 23));
        btncoursework.setPreferredSize(new java.awt.Dimension(240, 30));
        btncoursework.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncourseworkIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btntranscript, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(btncoursework, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(btnmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnmanagefinance, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btngradaudit, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitle)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmanageprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngradaudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncoursework, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmanagefinance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagefinanceIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagefinanceIdentifyResourceAssetsActionPerformed
    
    StudentFinance studentFinance = new StudentFinance(student);
    CardSequencePanel.add("StudentFinance", studentFinance);
    
    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    layout.show(CardSequencePanel, "StudentFinance");       

    }//GEN-LAST:event_btnmanagefinanceIdentifyResourceAssetsActionPerformed

    private void btnmanageprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageprofileActionPerformed
        // TODO add your handling code here:
StudentManageProfile manageProfilePanel = new StudentManageProfile(student);
    CardSequencePanel.add("StudentManageProfile", manageProfilePanel);
    
    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    layout.show(CardSequencePanel, "StudentManageProfile");


}//GEN-LAST:event_btnmanageprofileActionPerformed

    private void btngradauditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngradauditActionPerformed
        // TODO add your handling code here:
    StudentGraduation studentGraduation = new StudentGraduation(student);
    CardSequencePanel.add("StudentGraduation", studentGraduation);

    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    layout.show(CardSequencePanel, "StudentGraduation");

    }//GEN-LAST:event_btngradauditActionPerformed

    private void btnregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrationActionPerformed
        // TODO add your handling code here:
StudentRegistration studentRegister = new StudentRegistration(CardSequencePanel, student, business);
CardSequencePanel.add("StudentRegistration", studentRegister);

CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
layout.show(CardSequencePanel, "StudentRegistration");
}//GEN-LAST:event_btnregistrationActionPerformed

    private void btntranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranscriptActionPerformed
        // TODO add your handling code here:
    StudentTranscript studentTranscript = new StudentTranscript(student);
    CardSequencePanel.add("StudentTranscript", studentTranscript);
    
    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    layout.show(CardSequencePanel, "StudentTranscript");
    }//GEN-LAST:event_btntranscriptActionPerformed

    private void btncourseworkIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncourseworkIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    StudentCourse studentcourse = new StudentCourse(student);
    CardSequencePanel.add("StudentCourse", studentcourse);
    
    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    layout.show(CardSequencePanel, "StudentCourse");
    }//GEN-LAST:event_btncourseworkIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoursework;
    private javax.swing.JButton btngradaudit;
    private javax.swing.JButton btnmanagefinance;
    private javax.swing.JButton btnmanageprofile;
    private javax.swing.JButton btnregistration;
    private javax.swing.JButton btntranscript;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
