/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Profiles.StudentProfile;
import ManageStudentModel.Course;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amrin
 */


public class StudentFinance extends javax.swing.JPanel {

    private StudentProfile student;

    public StudentFinance(StudentProfile student) {
        this.student = student;
        initComponents();
        populateTable();
        updateBalanceField();
        btnpaytuition.addActionListener(e -> payTuitionAction());
        btnviewhistory.addActionListener(e -> viewHistoryAction());
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) studentfinancetable.getModel();
        model.setRowCount(0);

        List<Course> courses = student.getEnrolledCourses();
        for (Course c : courses) {
            String status = (student.getBalance() > 0) ? "Billed" : "Paid";
            model.addRow(new Object[]{c.getCourseId(), c.getCourseName(), c.getCredits(), status});
        }
    }

    private void updateBalanceField() {
        fieldbalance.setText(String.format("%.2f", student.getBalance()));
    }

    private void payTuitionAction() {
        if (student.getBalance() <= 0) {
            JOptionPane.showMessageDialog(this, "No balance to pay!", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        double amount = student.getBalance();
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Do you want to pay $" + amount + " tuition?", 
                "Confirm Payment", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            student.payTuition(amount);
            JOptionPane.showMessageDialog(this, "Payment Successful!");
            updateBalanceField();
            populateTable();
        }
    }

    private void viewHistoryAction() {
        List<String> history = student.getPaymentHistory();
        if (history.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No payment history available.", "History", JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder sb = new StringBuilder();
            for (String record : history) {
                sb.append(record).append("\n");
            }
            JOptionPane.showMessageDialog(this, sb.toString(), "Payment History", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentfinancetable = new javax.swing.JTable();
        lblcourseoffering = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        fieldbalance = new javax.swing.JTextField();
        btnpaytuition = new javax.swing.JButton();
        btnviewhistory = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitle.setText("STUDENT FINANCE");

        studentfinancetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Credit", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentfinancetable);

        lblcourseoffering.setText("Enrolled Courses");

        lblbalance.setText("Current Balance:");

        btnpaytuition.setText("Pay Tuition");

        btnviewhistory.setText("View History");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnback)
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltitle)
                            .addComponent(lblcourseoffering, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblbalance)
                        .addGap(18, 18, 18)
                        .addComponent(fieldbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnpaytuition)
                        .addGap(33, 33, 33)
                        .addComponent(btnviewhistory)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(lbltitle))
                .addGap(46, 46, 46)
                .addComponent(lblcourseoffering)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbalance)
                    .addComponent(fieldbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpaytuition)
                    .addComponent(btnviewhistory))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.previous(this.getParent());
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnpaytuition;
    private javax.swing.JButton btnviewhistory;
    private javax.swing.JTextField fieldbalance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblcourseoffering;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable studentfinancetable;
    // End of variables declaration//GEN-END:variables
}
